"""Build crawlable guide pages using only Python's standard library."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://www.ggmousepro.in'
PAGES = {
 'free-fire-settings': ('Free Fire Keyboard & Mouse Setup | GG Mouse Pro 3', 'Free Fire keyboard and mouse setup', 'Build a Free Fire keymap, align it with your HUD, and troubleshoot controls with this GG Mouse Pro 3 setup guide.', [
 ('Before you start', '<p>Keep a copy of your current Free Fire HUD before changing controls. These are suggested bindings, not an official preset or a guarantee of game compatibility. Check the game’s current rules on external input and third-party mapping before using them.</p>'),
 ('Connect and activate', '<ol><li><a href="/download">Install GG Mouse Pro 3</a> and connect your keyboard and mouse.</li><li>Confirm typing and pointer movement work in Android before opening the game.</li><li>Complete the <a href="/activation">activation method</a> available on your device.</li><li>Open your game profile in GG Mouse Pro and align the mapping controls with your current HUD. Save the profile before testing.</li></ol>'),
 ('Suggested keymap and customization', '<p>Use these as starting points and assign each key to the matching on-screen control. Existing <a href="/Free-Fire/Keymapping">Free Fire keymap templates</a> can help you compare layouts.</p><div class="table-wrap"><table><tr><th scope="col">Action</th><th scope="col">Suggested input</th></tr><tr><td>Movement</td><td>W / A / S / D</td></tr><tr><td>Jump</td><td>Space</td></tr><tr><td>Reload</td><td>R</td></tr><tr><td>Crouch</td><td>C</td></tr><tr><td>Interact</td><td>F</td></tr><tr><td>Weapon slots</td><td>1 / 2</td></tr></table></div><p>Test movement, camera control, and individual buttons separately in a permitted practice mode. Moving or resizing the HUD means you must realign your map.</p>'),
 ('Sensitivity and aim', '<p>Keep mouse DPI fixed while testing. Adjust one setting at a time and compare small target movements with wider turns. There is no universal best sensitivity: screen size, DPI, and the game’s own settings change the result. See the <a href="/sensitivity-guide">sensitivity guide</a> for a repeatable calibration process.</p>'),
 ('When a key misses its target', '<p>Check screen orientation, HUD scale, and whether the intended profile is active. If every key stops responding, check activation before moving individual bindings. For connection or permission failures, use the <a href="/troubleshooting">troubleshooting checklist</a>.</p>')]),
 'pubg-settings': ('PUBG Mobile Keyboard & Mouse Setup | GG Mouse Pro 3', 'PUBG Mobile keyboard and mouse setup', 'Plan PUBG Mobile keybindings, check device input, and diagnose mapping problems with a practical keyboard and mouse setup checklist.', [
 ('Check game rules and compatibility', '<p>This guide describes a mapping workflow, not verified support for every PUBG Mobile release. Check the publisher’s current rules before using third-party controls. Successful Android input does not establish permission to use it in a game.</p>'),
 ('Connect your devices', '<ol><li>Connect the keyboard and mouse and test them outside the game.</li><li><a href="/download">Install the app</a>, then follow the applicable <a href="/activation">activation guide</a>.</li><li>Preserve your existing HUD and create a separate profile for the layout you intend to test.</li><li>Align mapped controls with that layout. Save before entering a permitted practice session.</li></ol>'),
 ('Plan your PUBG keybindings', '<p>Start with WASD for movement, Space for jump, R for reload, and F for interaction. Assign distinct, comfortable keys to crouch, prone, inventory, and weapon selection. Add vehicle controls only after the basic layout works.</p><p>Check tap and hold behavior separately, especially for aiming and leaning. Avoid assigning one key to multiple actions unless you explicitly intend that behavior.</p>'),
 ('Camera and sensitivity', '<p>Calibrate the camera before adjusting scoped sensitivity. Use a fixed mouse DPI and repeat the same motion at each setting. Keep notes so you can restore your previous values. Follow the <a href="/sensitivity-guide">sensitivity guide</a>; copied settings rarely match every phone.</p>'),
 ('Macros and activation problems', '<p>Automation may be restricted by the game. Keep normal bindings working before considering advanced features, and do not assume macros or recoil automation are permitted. The <a href="/macro-guide">macro guide</a> explains basic testing and how to avoid overlapping triggers.</p><p>If input disappears after restarting the device, inspect activation status first. See <a href="/troubleshooting">troubleshooting</a> before rebuilding the profile.</p>')]),
 'android-gaming-peripherals': ('Android Gaming Keyboards & Mice: Buying Guide', 'Choose a keyboard and mouse for Android gaming', 'Compare wired, Bluetooth, and receiver-based keyboard and mouse setups for Android, with a practical compatibility checklist before buying.', [
 ('Start with compatibility', '<p>Choose around your phone’s connections and the games you use. A keyboard that types in Android is not proof that a game supports it. Confirm the phone’s USB host support, connector type, and the peripheral maker’s Android compatibility information before ordering.</p><p>This is a selection guide, not a hands-on product review. No products have been tested for this article and this page contains no affiliate links.</p>'),
 ('Compare connection types', '<div class="table-wrap"><table><tr><th scope="col">Connection</th><th scope="col">What to check</th><th scope="col">Useful for</th></tr><tr><td>Wired USB</td><td>USB host support, adapter and hub power needs</td><td>A desk setup without peripheral batteries</td></tr><tr><td>Bluetooth</td><td>Android support, pairing and wake behavior</td><td>A portable setup with fewer cables</td></tr><tr><td>USB receiver</td><td>Receiver connector, hub space and power</td><td>Wireless peripherals that use a dedicated receiver</td></tr></table></div>'),
 ('Keyboard checklist', '<p>Look for a comfortable layout, clearly marked keys, and enough space beside the keyboard for the mouse. A compact layout saves desk space; a larger layout can make extra bindings easier to reach. Check whether lighting or remapping requires desktop-only software and whether settings persist when disconnected.</p>'),
 ('Mouse and adapter checklist', '<p>Prioritize a comfortable shape and adjustable sensitivity over a high maximum DPI number. Check whether side buttons work without a desktop driver. For a hub, count the ports you need and verify power and charging compatibility with your exact phone. A charging port on a hub does not guarantee simultaneous charging and USB host operation.</p>'),
 ('Test before committing', '<ol><li>Check the seller’s return terms and exact model specifications.</li><li>Test typing and pointer movement in Android.</li><li>Test both devices together, including after sleep and reconnection.</li><li>Use the <a href="/keymapping">keymapping guide</a> to test a permitted game profile.</li></ol><p>For Android’s keyboard setup instructions, see <a href="https://support.google.com/android/answer/14114879">Google’s physical keyboard help</a>.</p>')]),
 'macro-guide': ('GG Mouse Pro 3 Macro Guide: Setup & Troubleshooting', 'Set up and troubleshoot macros', 'Understand macro triggers, timing, and troubleshooting in GG Mouse Pro 3, with a cautious workflow for testing repetitive input.', [
 ('What is a macro?', '<p>A macro groups input actions under a trigger. Availability and editor labels can vary by app version or plan. Start with ordinary <a href="/keymapping">keybindings</a> so you can distinguish a mapping problem from a macro problem.</p><p>Only use automation where the app or game permits it. A working macro does not mean it complies with game rules, and no guide can guarantee protection from account penalties.</p>'),
 ('Create a small test', '<ol><li>Save a copy of the working profile.</li><li>Open the macro controls available in your version; the <a href="/#tutorials">macro video tutorial</a> provides a visual reference.</li><li>Choose a trigger that is not already assigned to another action.</li><li>Begin with one action and one execution, using a permitted test environment.</li><li>Save and test. Add another action only after the first works reliably.</li></ol>'),
 ('Timing and trigger behavior', '<p>Distinguish a single press from a held or repeated trigger. Begin with a single-run sequence; verify how to stop it before enabling repetition. If an action is skipped, increase the interval gradually and retest. Long sequences are harder to diagnose and may fail when the screen changes.</p>'),
 ('Troubleshoot or restore', '<p>If a sequence fires twice, inspect duplicate bindings and repeat options. If the wrong button is pressed, check the current HUD against the mapped coordinates. If nothing responds, test a normal binding and review <a href="/activation">activation</a>.</p><p>Disable the macro and restore the saved profile if behavior is unpredictable. When contacting <a href="/contact">support</a>, include the app version, device model, trigger type, and a short description of the expected action.</p>')]),
 'keymapping': ('Android Keyboard & Mouse Keymapping | GG Mouse Pro 3', 'Build your first keyboard and mouse keymap', 'Learn how to connect Android input devices, align a keymap with your game HUD, and save a profile in GG Mouse Pro 3.', [
 ('Test Android input first', '<p>Connect your devices through a supported USB adapter or Bluetooth. Type in a text field and check pointer movement. If either fails, solve the connection issue before changing game mappings.</p>'),
 ('Create a profile', '<ol><li>Complete <a href="/activation">activation</a> and select the intended game profile.</li><li>Use a stable screen orientation and save your in-game HUD.</li><li>Place each mapping over the matching on-screen control.</li><li>Assign distinct keys, then save the profile.</li><li>Test movement, buttons, and camera behavior individually where permitted.</li></ol>'),
 ('Choose a game guide', '<p>Use the <a href="/free-fire-settings">Free Fire setup guide</a> or <a href="/pubg-settings">PUBG Mobile setup guide</a> for suggested bindings. These are starting points to customize, not guaranteed compatible presets.</p>'),
 ('Keep the layout consistent', '<p>A HUD change, screen resolution change, or different orientation can shift the target buttons. Save separate profiles for different layouts. If input stops altogether, follow <a href="/troubleshooting">troubleshooting</a> before remapping everything.</p>')]),
 'sensitivity-guide': ('Mouse Sensitivity on Android | GG Mouse Pro 3 Guide', 'Calibrate mouse sensitivity on Android', 'Use a repeatable process to tune mouse DPI, camera movement, and scoped sensitivity without relying on universal presets.', [
 ('Establish a baseline', '<p>Record your mouse DPI, app sensitivity, game sensitivity, and screen orientation. Keep the mouse surface and available movement space consistent. Save your current profile before making changes.</p>'),
 ('Change one variable at a time', '<ol><li>Keep DPI fixed and choose a repeatable mouse movement.</li><li>Observe how far the camera turns in a permitted practice mode.</li><li>Adjust one sensitivity control slightly.</li><li>Repeat the same movement and record the result.</li><li>After broad turns feel comfortable, test small adjustments and scoped movement separately.</li></ol>'),
 ('Separate sensitivity from connection problems', '<p>Overshooting a target can call for a lower setting. Missing input, disconnects, and pauses require a <a href="/troubleshooting">connection check</a>. Changing sensitivity will not repair an unstable adapter or expired activation.</p>'),
 ('Save settings per layout', '<p>Record the final values with the game profile. Recheck after HUD or display changes. Return to the <a href="/free-fire-settings">Free Fire</a> or <a href="/pubg-settings">PUBG guide</a> to verify the rest of the bindings.</p>')]),
 'troubleshooting': ('GG Mouse Pro Troubleshooting: Input & Activation', 'Troubleshoot input and activation', 'Diagnose Android keyboard, mouse, activation, and keymap issues in order before rebuilding your GG Mouse Pro profile.', [
 ('Keyboard or mouse is not detected', '<p>Test the device outside the game. For USB, reconnect the adapter and test one peripheral at a time. Check your phone’s USB host support and any device-specific OTG setting. For Bluetooth, confirm pairing and battery state. A failure outside the game points to the connection rather than the keymap.</p>'),
 ('Android input works but game input does not', '<p>Inspect the app’s activation status and requested permissions. Follow the appropriate <a href="/wireless-activation">wireless</a> or <a href="/wired-activation">wired activation guide</a>. Confirm that you selected the correct game profile and saved it.</p>'),
 ('Keys press the wrong controls', '<p>Compare the current HUD with the saved keymap. Check orientation, button size, and screen scaling. Realign one mapping and test it before changing the entire profile. See <a href="/keymapping">keymapping basics</a>.</p>'),
 ('Prepare a useful support request', '<p>Include your phone model, Android version, app version, connection type, activation method, and exact error message. State whether input works outside the game and what changed before the problem started. Do not include passwords or pairing codes. Send these details through the <a href="/contact">support page</a>.</p>')])
}

def render(slug, title, heading, description, sections, hub=False):
    url=BASE+'/'+slug
    schema={'@context':'https://schema.org','@graph':[
      {'@type':'CollectionPage' if hub else 'Article','headline':heading,'description':description,'url':url,'mainEntityOfPage':url,'publisher':{'@type':'Organization','name':'GG Mouse Pro 3','url':BASE}},
      {'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'Guides','item':BASE+'/guides'}]+([] if hub else [{'@type':'ListItem','position':3,'name':heading,'item':url}])}]}
    content=''.join(f'<section id="section-{i}"><h2>{escape(h)}</h2>{body}</section>' for i,(h,body) in enumerate(sections))
    toc=''.join(f'<a href="#section-{i}">{escape(h)}</a>' for i,(h,_) in enumerate(sections))
    page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title><meta name="description" content="{escape(description,quote=True)}"><link rel="canonical" href="{url}">
<meta property="og:type" content="{'website' if hub else 'article'}"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="{url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{escape(title,quote=True)}"><meta name="twitter:description" content="{escape(description,quote=True)}"><meta name="theme-color" content="#2563eb">
<link rel="stylesheet" href="/css/guides.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head>
<body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/">GG Mouse Pro 3</a><nav aria-label="Main navigation"><a href="/guides">Guides</a><a href="/activation">Activation</a><a href="/faq">FAQ</a><a href="/download">Download</a></nav></header>
<main id="main"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/guides">Guides</a>{'' if hub else ' / '+escape(heading)}</nav><div class="hero"><span class="eyebrow">GG MOUSE PRO 3 · SETUP &amp; GUIDES</span><h1>{escape(heading)}</h1><p class="intro">{escape(description)}</p><a class="button" href="/download">Download &amp; set up</a><a href="/contact">Get support</a></div>
<div class="layout"><article>{content}<aside class="callout"><h2>Continue your setup</h2><p><a href="/guides">Browse all guides</a> or <a href="/activation">choose an activation method</a>.</p><a class="button" href="/download">Get GG Mouse Pro 3</a></aside></article><aside class="contents" aria-label="On this page"><strong>On this page</strong>{toc}</aside></div></main>
<footer><nav aria-label="Footer"><a href="/download">Download</a><a href="/contact">Support</a><a href="/privacy-policy">Privacy</a><a href="/terms">Terms</a></nav><p>GG Mouse Pro 3 · Android keyboard and mouse guides</p></footer></body></html>'''
    (ROOT/(slug+'.html')).write_text(page,encoding='utf-8')

for slug, data in PAGES.items(): render(slug,*data)
cards=''.join(f'<div class="card"><h3><a href="/{slug}">{escape(data[1])}</a></h3><p>{escape(data[2])}</p></div>' for slug,data in PAGES.items())
render('guides','GG Mouse Pro 3 Guides: Setup, Keymaps & Hardware','Keyboard, mouse, and activation guides','Start with installation, build your game keymap, and solve common input problems with GG Mouse Pro 3.',[
 ('Start here','<ol><li><a href="/download">Download and install the app</a>.</li><li><a href="/activation">Choose your activation method</a>.</li><li><a href="/keymapping">Build and test your first keymap</a>.</li></ol>'),
 ('Explore the guides','<div class="grid">'+cards+'</div>')],hub=True)
